const ACTIVATION = "ACTIVATION";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const LOGIN_WITH_GOOGLE = "LOGIN_WITH_GOOGLE";
const LOGIN_WITH_FORM = "LOGIN_WITH_FORM";
const LOGIN_WITH_FORM_EROR = "LOGIN_WITH_FORM_EROR";
const PRODUCT_LIST = "PRODUCT_LIST";
const HANDLE_LOADING = "HANDLE_LOADING";
const GET_ADDRESS_DEFAULT = "GET_ADDRESS_DEFAULT"
 

const TYPE = {
    HANDLE_LOADING: HANDLE_LOADING,
    ACTIVATION: ACTIVATION,
    LOGIN: LOGIN,
    LOGOUT: LOGOUT,
    LOGIN_WITH_GOOGLE: LOGIN_WITH_GOOGLE,
    LOGIN_WITH_FORM: LOGIN_WITH_FORM,
    PRODUCT_LIST: PRODUCT_LIST,
    LOGIN_WITH_FORM_EROR: LOGIN_WITH_FORM_EROR,
    GET_ADDRESS_DEFAULT: GET_ADDRESS_DEFAULT
}

export default TYPE;