const ACTIVATION = "ACTIVATION";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const LOGIN_WITH_GOOGLE = "LOGIN_WITH_GOOGLE";
const LOGIN_WITH_FORM = "LOGIN_WITH_FORM";
const REGISTER_WITH_FORM = "REGISTER_WITH_FORM";
const PRODUCT_LIST = "PRODUCT_LIST";
 

const TYPE = {
    ACTIVATION: ACTIVATION,
    LOGIN: LOGIN,
    LOGOUT: LOGOUT,
    LOGIN_WITH_GOOGLE: LOGIN_WITH_GOOGLE,
    LOGIN_WITH_FORM: LOGIN_WITH_FORM,
    REGISTER_WITH_FORM: REGISTER_WITH_FORM,
    PRODUCT_LIST: PRODUCT_LIST,
     
}

export default TYPE;